/**
 * Deterministic Hackathon Demo Seed Data for MediConnect
 */

const users = [
  {
    _id: 'user_cust_1',
    name: 'Rahul Verma',
    email: 'customer@mediconnect.com',
    phone: '+91 98765 43210',
    password: 'password123',
    role: 'customer',
    address: 'E-3 Arera Colony',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4265, 23.2135] },
    isActive: true,
  },
  {
    _id: 'user_pharm_1',
    name: 'Vikram (ABC Medical)',
    email: 'abc@mediconnect.com',
    phone: '+91 98220 11223',
    password: 'password123',
    role: 'pharmacist',
    address: 'Zone-II, MP Nagar',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4338, 23.2332] },
    isActive: true,
  },
  {
    _id: 'user_pharm_1_alt',
    name: 'Pharmacist ABC',
    email: 'pharmacist@mediconnect.com',
    phone: '+91 98220 11223',
    password: 'password123',
    role: 'pharmacist',
    address: 'Zone-II, MP Nagar',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4338, 23.2332] },
    isActive: true,
  },
  {
    _id: 'user_pharm_2',
    name: 'Anita (HealthPlus)',
    email: 'healthplus@mediconnect.com',
    phone: '+91 98110 44556',
    password: 'password123',
    role: 'pharmacist',
    address: 'TT Nagar, New Market',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.3995, 23.2422] },
    isActive: true,
  },
  {
    _id: 'user_pharm_3',
    name: 'Suresh (City Care)',
    email: 'citycare@mediconnect.com',
    phone: '+91 98330 99887',
    password: 'password123',
    role: 'pharmacist',
    address: 'Main Road, Kolar',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4150, 23.1780] },
    isActive: true,
  },
  {
    _id: 'user_pharm_4',
    name: 'Pooja (MediCare)',
    email: 'medicare@mediconnect.com',
    phone: '+91 98440 55667',
    password: 'password123',
    role: 'pharmacist',
    address: 'Hoshangabad Road',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4480, 23.1950] },
    isActive: true,
  },
  {
    _id: 'user_pharm_5',
    name: 'Rajesh (Apollo)',
    email: 'apollo@mediconnect.com',
    phone: '+91 98550 66778',
    password: 'password123',
    role: 'pharmacist',
    address: 'Bittan Market, Arera Colony',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4290, 23.2160] },
    isActive: true,
  },
  {
    _id: 'user_admin_1',
    name: 'MediConnect Admin',
    email: 'admin@mediconnect.com',
    phone: '+91 99999 00000',
    password: 'adminpassword',
    role: 'admin',
    address: 'DB City Mall, MP Nagar',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4350, 23.2350] },
    isActive: true,
  },
];

const pharmacies = [
  {
    _id: 'pharm_1',
    name: 'ABC Medical Store',
    owner: 'user_pharm_1',
    phone: '+91 98220 11223',
    address: 'Zone-II, MP Nagar',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4338, 23.2332] },
    openingHours: '8:00 AM - 11:00 PM',
    licenseNumber: 'DL-MP-2023-9081',
    verificationStatus: 'verified',
    rating: 4.9,
    totalConfirmations: 45,
    unavailableReports: 0,
    createdAt: new Date(Date.now() - 30 * 86400000),
  },
  {
    _id: 'pharm_2',
    name: 'HealthPlus Pharmacy',
    owner: 'user_pharm_2',
    phone: '+91 98110 44556',
    address: 'TT Nagar, New Market',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.3995, 23.2422] },
    openingHours: '24 Hours Open',
    licenseNumber: 'DL-MP-2022-7712',
    verificationStatus: 'verified',
    rating: 4.8,
    totalConfirmations: 30,
    unavailableReports: 1,
    createdAt: new Date(Date.now() - 60 * 86400000),
  },
  {
    _id: 'pharm_3',
    name: 'City Care Pharmacy',
    owner: 'user_pharm_3',
    phone: '+91 98330 99887',
    address: 'Main Road, Kolar',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4150, 23.1780] },
    openingHours: '9:00 AM - 10:00 PM',
    licenseNumber: 'DL-MP-2024-3401',
    verificationStatus: 'verified',
    rating: 4.6,
    totalConfirmations: 18,
    unavailableReports: 0,
    createdAt: new Date(Date.now() - 15 * 86400000),
  },
  {
    _id: 'pharm_4',
    name: 'MediCare Pharmacy',
    owner: 'user_pharm_4',
    phone: '+91 98440 55667',
    address: 'Hoshangabad Road',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4480, 23.1950] },
    openingHours: '8:30 AM - 10:30 PM',
    licenseNumber: 'DL-MP-2021-1120',
    verificationStatus: 'verified',
    rating: 4.7,
    totalConfirmations: 22,
    unavailableReports: 1,
    createdAt: new Date(Date.now() - 90 * 86400000),
  },
  {
    _id: 'pharm_5',
    name: 'Apollo Local Care',
    owner: 'user_pharm_5',
    phone: '+91 98550 66778',
    address: 'Bittan Market, Arera Colony',
    city: 'Bhopal',
    location: { type: 'Point', coordinates: [77.4290, 23.2160] },
    openingHours: '8:00 AM - 11:30 PM',
    licenseNumber: 'DL-MP-2023-4512',
    verificationStatus: 'verified',
    rating: 4.9,
    totalConfirmations: 38,
    unavailableReports: 0,
    createdAt: new Date(Date.now() - 40 * 86400000),
  },
];

const medicines = [
  {
    _id: 'med_1',
    name: 'Paracetamol 650',
    genericName: 'Acetaminophen 650mg',
    category: 'Pain Relief & Fever',
    dosageForm: 'Tablet',
    strength: '650 mg',
    manufacturer: 'Dolo / Micro Labs',
    prescriptionRequired: false,
    description: 'Antipyretic and analgesic for fever and pain relief.',
    aliases: ['Dolo 650', 'Calpol 650', 'Crocin 650', 'P-650', 'Paracetamol'],
  },
  {
    _id: 'med_2',
    name: 'Cetirizine 10',
    genericName: 'Cetirizine Hydrochloride 10mg',
    category: 'Allergy & Respiratory',
    dosageForm: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Dr. Reddy Labs',
    prescriptionRequired: false,
    description: 'Antihistamine for allergy, sneezing, and cold relief.',
    aliases: ['Cetzine', 'Alerid', 'Zyrtec', 'Okacet', 'Cetirizine'],
  },
  {
    _id: 'med_3',
    name: 'ORS',
    genericName: 'Oral Rehydration Salts (WHO Formula)',
    category: 'First Aid & Rehydration',
    dosageForm: 'Sachet',
    strength: '21.8 g Sachet',
    manufacturer: 'FDC / Electral',
    prescriptionRequired: false,
    description: 'WHO formula to restore electrolytes and hydration.',
    aliases: ['Electral', 'Walyte', 'Prolyte', 'ORS Powder'],
  },
  {
    _id: 'med_4',
    name: 'Ibuprofen 400',
    genericName: 'Ibuprofen 400mg',
    category: 'Pain Relief & Fever',
    dosageForm: 'Tablet',
    strength: '400 mg',
    manufacturer: 'Abbott',
    prescriptionRequired: false,
    description: 'NSAID for muscular pain, headaches, and inflammation.',
    aliases: ['Brufen 400', 'Combiflam', 'Combiflame', 'Ibugesic'],
  },
  {
    _id: 'med_5',
    name: 'Amoxicillin 500',
    genericName: 'Amoxicillin 500mg',
    category: 'Antibiotics',
    dosageForm: 'Capsule',
    strength: '500 mg',
    manufacturer: 'GSK',
    prescriptionRequired: true,
    description: 'Broad-spectrum antibiotic.',
    aliases: ['Mox 500', 'Novamox', 'Amoxil'],
  },
  {
    _id: 'med_6',
    name: 'Azithromycin 500',
    genericName: 'Azithromycin 500mg',
    category: 'Antibiotics',
    dosageForm: 'Tablet',
    strength: '500 mg',
    manufacturer: 'Cipla',
    prescriptionRequired: true,
    description: 'Antibiotic for bacterial infections.',
    aliases: ['Azee 500', 'Azithral', 'Zithromax'],
  },
  {
    _id: 'med_7',
    name: 'Pantoprazole 40',
    genericName: 'Pantoprazole 40mg',
    category: 'Gastrointestinal',
    dosageForm: 'Tablet',
    strength: '40 mg',
    manufacturer: 'Alkem',
    prescriptionRequired: false,
    description: 'Reduces stomach acid and relieves heartburn.',
    aliases: ['Pan 40', 'Pantocid', 'Pantodac'],
  },
  {
    _id: 'med_8',
    name: 'Metformin 500',
    genericName: 'Metformin Hydrochloride 500mg',
    category: 'Diabetes',
    dosageForm: 'Tablet',
    strength: '500 mg',
    manufacturer: 'USV / Glycomet',
    prescriptionRequired: true,
    description: 'Helps manage blood glucose levels.',
    aliases: ['Glycomet 500', 'Glucophage', 'Obimet'],
  },
];

const nowMs = Date.now();
const inventories = [
  // ABC Medical Store
  {
    _id: 'inv_1',
    pharmacy: 'pharm_1',
    medicine: 'med_1', // Paracetamol 650
    status: 'available',
    quantity: 120,
    unitPrice: 32,
    lastUpdated: new Date(nowMs - 5 * 60 * 1000), // 5 min ago
    notes: 'In stock at counter',
  },
  {
    _id: 'inv_2',
    pharmacy: 'pharm_1',
    medicine: 'med_2', // Cetirizine 10
    status: 'available',
    quantity: 80,
    unitPrice: 22,
    lastUpdated: new Date(nowMs - 15 * 60 * 1000),
  },
  {
    _id: 'inv_3',
    pharmacy: 'pharm_1',
    medicine: 'med_3', // ORS
    status: 'available',
    quantity: 150,
    unitPrice: 21,
    lastUpdated: new Date(nowMs - 10 * 60 * 1000),
  },
  {
    _id: 'inv_4',
    pharmacy: 'pharm_1',
    medicine: 'med_6', // Azithromycin 500
    status: 'available',
    quantity: 40,
    unitPrice: 115,
    lastUpdated: new Date(nowMs - 8 * 60 * 1000),
  },

  // HealthPlus Pharmacy
  {
    _id: 'inv_5',
    pharmacy: 'pharm_2',
    medicine: 'med_1', // Paracetamol 650
    status: 'available',
    quantity: 60,
    unitPrice: 30,
    lastUpdated: new Date(nowMs - 12 * 60 * 1000),
  },
  {
    _id: 'inv_6',
    pharmacy: 'pharm_2',
    medicine: 'med_4', // Ibuprofen 400
    status: 'available',
    quantity: 90,
    unitPrice: 28,
    lastUpdated: new Date(nowMs - 20 * 60 * 1000),
  },
  {
    _id: 'inv_7',
    pharmacy: 'pharm_2',
    medicine: 'med_7', // Pantoprazole 40
    status: 'available',
    quantity: 110,
    unitPrice: 75,
    lastUpdated: new Date(nowMs - 25 * 60 * 1000),
  },

  // City Care Pharmacy
  {
    _id: 'inv_8',
    pharmacy: 'pharm_3',
    medicine: 'med_2', // Cetirizine 10
    status: 'available',
    quantity: 50,
    unitPrice: 20,
    lastUpdated: new Date(nowMs - 30 * 60 * 1000),
  },
  {
    _id: 'inv_9',
    pharmacy: 'pharm_3',
    medicine: 'med_3', // ORS
    status: 'low',
    quantity: 5,
    unitPrice: 21,
    lastUpdated: new Date(nowMs - 4 * 3600 * 1000),
  },
  {
    _id: 'inv_10',
    pharmacy: 'pharm_3',
    medicine: 'med_8', // Metformin 500
    status: 'available',
    quantity: 75,
    unitPrice: 42,
    lastUpdated: new Date(nowMs - 35 * 60 * 1000),
  },
  {
    _id: 'inv_11',
    pharmacy: 'pharm_3',
    medicine: 'med_1', // Paracetamol 650
    status: 'out',
    quantity: 0,
    unitPrice: 32,
    lastUpdated: new Date(nowMs - 2 * 3600 * 1000),
  },

  // MediCare Pharmacy
  {
    _id: 'inv_12',
    pharmacy: 'pharm_4',
    medicine: 'med_6', // Azithromycin 500
    status: 'available',
    quantity: 30,
    unitPrice: 118,
    lastUpdated: new Date(nowMs - 14 * 60 * 1000),
  },
  {
    _id: 'inv_13',
    pharmacy: 'pharm_4',
    medicine: 'med_1', // Paracetamol 650
    status: 'low',
    quantity: 4,
    unitPrice: 32,
    lastUpdated: new Date(nowMs - 6 * 3600 * 1000),
  },
  {
    _id: 'inv_14',
    pharmacy: 'pharm_4',
    medicine: 'med_5', // Amoxicillin 500
    status: 'available',
    quantity: 45,
    unitPrice: 88,
    lastUpdated: new Date(nowMs - 18 * 60 * 1000),
  },

  // Apollo Local Care
  {
    _id: 'inv_15',
    pharmacy: 'pharm_5',
    medicine: 'med_8', // Metformin 500
    status: 'available',
    quantity: 100,
    unitPrice: 40,
    lastUpdated: new Date(nowMs - 10 * 60 * 1000),
  },
  {
    _id: 'inv_16',
    pharmacy: 'pharm_5',
    medicine: 'med_7', // Pantoprazole 40
    status: 'available',
    quantity: 80,
    unitPrice: 70,
    lastUpdated: new Date(nowMs - 12 * 60 * 1000),
  },
];

const requests = [
  {
    _id: 'req_demo_1',
    customer: 'user_cust_1',
    pharmacy: 'pharm_1',
    medicine: 'med_1',
    status: 'pending',
    customerNote: 'Need 2 strips of Paracetamol 650',
    pharmacistNote: '',
    createdAt: new Date(nowMs - 3 * 60 * 1000),
    respondedAt: null,
  },
];

const reservations = [
  {
    _id: 'res_demo_1',
    customer: 'user_cust_1',
    pharmacy: 'pharm_1',
    medicine: 'med_1',
    quantity: 2,
    pickupCode: 'MC-8421',
    status: 'active',
    expiresAt: new Date(nowMs + 3 * 3600 * 1000),
    collectedAt: null,
    createdAt: new Date(nowMs - 10 * 60 * 1000),
  },
];

const reports = [];

module.exports = {
  users,
  pharmacies,
  medicines,
  inventories,
  requests,
  reservations,
  reports,
};
